#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5 6

bspc config focused_border_color "#83A598"
bspc config border_width         3
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config single_monocle		 true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

numlockx on
xsetroot -cursor_name left_ptr
feh --bg-scale ~/Pictures/wallpaper.jpg
killall polybar
polybar top
dunst
picom
nm-applet
xrandr --output HDMI-0 --brightness 0.9
