#! /bin/sh

sxhkd &

bspc monitor -d 1 2 3 4 5

bspc config border_width         3
bspc config window_gap           4

bspc config split_ratio          0.50
bspc config single_monocle		 true
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

numlockx on
xset -b off -s 600
xsetroot -cursor_name left_ptr
feh --bg-scale ~/Pictures/wallpaper.jpg
sh ~/.config/bspwm/launch.sh
killall polybar
polybar top
dunst
picom
